name: MLflow CI

on:
  push:
    branches: ["main"]     # setiap push ke main
  workflow_dispatch:        # bisa dijalankan manual dari GitHub UI

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"

      - name: Install MLflow + dependencies
        run: |
          conda env update -f MLProject/conda.yaml

      - name: Run MLflow Project
        run: |
          mlflow run MLProject \
            -P epochs=10 \
            -P batch_size=32
