name: CI MLflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  train:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Miniconda (for MLflow Projects)
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          mamba-version: "*"
          python-version: "3.10"   # TensorFlow & mlflow paling stabil di 3.10

      # 3. Verify folder structure
      - name: Check Project files
        run: |
          echo "Available files:"
          ls -R .

      # 4. Install mlflow in base conda env (cannot install inside project)
      - name: Install MLflow
        run: |
          conda install -y pip
          pip install mlflow

      # 5. Run MLflow Project
      - name: Run MLflow Project
        run: |
          mlflow run Project
