name: CI MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Miniconda (for MLflow Projects)
      # TensorFlow & mlflow paling stabil di 3.10

      # 3. Verify folder structure
      - name: Check Project files
        run: |
          echo "Available files:"
          ls -R .

      # 4. Install mlflow in base conda env (cannot install inside project)
      - name: Install MLflow
        run: |
          conda install -y pip
          pip install mlflow

      # 5. Run MLflow Project
      - name: Run MLflow Project
        run: |
          mlflow run Project
